#!/bin/bash


cat "$1"| sed  's/src="\//src="https:\/\/gitcdn.link\/repo\/zerom3457\/peruconta\/main\/blog\/public\//g'| sed  's/href="\//href="https:\/\/gitcdn.link\/repo\/zerom3457\/peruconta\/main\/blog\/public\//g'  >index2z.html
cat index2z.html|sed  's/https:\/\/gitcdn.link\/repo\/zerom3457\/peruconta\/main\//https:\/\/zerom3457.github.io\/peruconta\//g' >"$1"

